version: '3'
 
services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "6034:3307"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata: